**Saniya Sayyed | 221A014 | 37 / RL EXP 02**

**UPPER CONFIDENCE BOUND ALGORITHM**

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
#Random selection
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#Importing the dataset
dataset = pd.read_csv('/content/Ads_Optimisation - Ads_Optimisation.csv')
dataset.head()

Razeen Siddiqui / 232A003 / 57

   Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0     1     0     0     0     1     0     0     0     1      0
1     0     0     0     0     0     0     0     0     1      0
2     0     0     0     0     0     0     0     0     0      0
3     0     1     0     0     0     0     0     1     0      0
4     0     0     0     0     0     0     0     0     0      0

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
dataset.info()

Razeen Siddiqui / 232A003 / 57
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ad 1    10000 non-null  int64
 1   Ad 2    10000 non-null  int64
 2   Ad 3    10000 non-null  int64
 3   Ad 4    10000 non-null  int64
 4   Ad 5    10000 non-null  int64
 5   Ad 6    10000 non-null  int64
 6   Ad 7    10000 non-null  int64
 7   Ad 8    10000 non-null  int64
 8   Ad 9    10000 non-null  int64
 9   Ad 10   10000 non-null  int64
dtypes: int64(10)
memory usage: 781.4 KB

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
#iMPLEMENTING Random Selection
import random
N = 10000
d = 10
ads_selected_random = []
total_reward_random = 0
for n in range(0, N):
  ad = random.randrange(d)
  ads_selected_random.append(ad)
  reward = dataset.values[n, ad]
  total_reward_random = total_reward_random + reward

Razeen Siddiqui / 232A003 / 57

In [ ]:
  print("Saniya Sayyed | 221A014 | 37")
  total_reward_random

Razeen Siddiqui / 232A003 / 57

np.int64(1257)

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
ads_selected_random[0:50]

Razeen Siddiqui / 232A003 / 57

[3,
 7,
 7,
 9,
 6,
 9,
 0,
 6,
 0,
 9,
 9,
 2,
 5,
 3,
 8,
 3,
 7,
 4,
 0,
 9,
 6,
 3,
 5,
 0,
 3,
 8,
 1,
 8,
 1,
 0,
 6,
 3,
 5,
 3,
 5,
 5,
 4,
 3,
 1,
 4,
 1,
 2,
 8,
 8,
 1,
 4,
 5,
 7,
 3,
 4]

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
#Implementing UCB
import math
N = 10000
d = 10
ads_selected =[]
numbers_of_selections = [0] * d
sums_of_rewards = [0] * d
total_reward = 0

for n in range(0, N):
    ad=0
    max_upper_bound = 0
    for i in range(0, d):
        if(numbers_of_selections[i] > 0):
            average_reward = sums_of_rewards[i] / numbers_of_selections[i]
            delta_i = math.sqrt(2 * math.log(n+1) / numbers_of_selections[i])
            upper_bound = average_reward + delta_i
        else:
            upper_bound = 1e400
        if upper_bound > max_upper_bound:
            max_upper_bound = upper_bound
            ad = i
    ads_selected.append(ad)
    numbers_of_selections[ad] +=1
    reward = dataset.values[n, ad]
    sums_of_rewards[ad] += reward
    total_reward += reward

Razeen Siddiqui / 232A003 / 57

Display Result

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
total_reward

Razeen Siddiqui / 232A003 / 57

np.int64(2125)

Final Comparison

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
print(f"Total Reward (Random Selection): {total_reward_random}")
print(f"Total Reward (UCB): {total_reward}")

Razeen Siddiqui / 232A003 / 57
Total Reward (Random Selection): 1257
Total Reward (UCB): 2125

In [ ]:
print("Saniya Sayyed | 221A014 | 37")
pd.Series(ads_selected).tail(1000).value_counts()

Razeen Siddiqui / 232A003 / 57

4    771
0    106
3     34
7     34
2     26
1      7
6      7
8      6
9      5
5      4
Name: count, dtype: int64